### ISSUE TITLE
Rebase does not working after update to 11.1.3

### ISSUE THREAD

**Issue by vitalyzhakov** [sameersbn/docker-gitlab#1711]
Hello!

After updating to 11.1.3 *rebase on merge request* does not working.

In githost.log i see
```
 ERROR -> MergeRequests::RebaseService error /gitaly-ssh upload-pack: 1: /gitaly-ssh upload-pack: /gitaly-ssh: not found

fatal: Could not read from remote repository.
```

**Comment by laqiguy** [comment]
Same problem. pls need fix

**Comment by Chegevarich** [comment]
Same

**Comment by S-Mak1** [comment]
+

**Comment by Uporaba1** [comment]
#vitaliyandreevichpochini

**Comment by laqiguy** [comment]
∆
∆  ∆

**Comment by laqiguy** [comment]
∆
∆  ∆

**Comment by solidnerd** [comment]
Which docker tag do you use at the moment ? `:latest` or `11.1.3`

**Comment by vitalyzhakov** [comment]
@solidnerd , I use `sameersbn/gitlab:11.1.3`

**Comment by solidnerd** [comment]
I think this is fixed with `11.2.0` I tested it on this version and it was working. Wait for the release and check it out afterwards otherwise reopen this issue.

**Comment by solidnerd** [comment]
11.2.0 is released. Try this Out if IT wont fix your Issue reopen it.

**Comment by arian** [comment]
We're using 11.2.3  and still get:

```
September 04, 2018 12:28 -> INFO -> MergeRequests::RebaseService info (symbaloo/main!1487): rebase started

September 04, 2018 12:28 -> ERROR -> MergeRequests::RebaseService error (symbaloo/main!1487): Rebase failed. Please rebase locally

September 04, 2018 12:28 -> ERROR -> MergeRequests::RebaseService error (symbaloo/main!1487): /gitaly-ssh upload-pack: 1: /gitaly-ssh upload-pack: /gitaly-ssh: not found

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.
```

**Comment by leslau** [comment]
this bug still on 11.2.3, when creating merge request from fork

**Comment by tvtamas** [comment]
We are experiencing this issue with `11.2.3`.

Docker containers:

*  `sameersbn/postgresql:10`
*  `sameersbn/gitlab:11.2.3`
*  `sameersbn/redis:4.0.9-1`
*  `registry:2.4.1`

```
# Logfile created on 2018-09-10 08:29:12 +0000 by logger.rb/56815
September 10, 2018 08:29 -> INFO -> MergeRequests::RebaseService info (<redacted>): rebase started
September 10, 2018 08:29 -> ERROR -> MergeRequests::RebaseService error (<redacted>): Rebase failed. Please rebase locally
September 10, 2018 08:29 -> ERROR -> MergeRequests::RebaseService error (<redacted>): /gitaly-ssh upload-pack: 1: /gitaly-ssh upload-pack: /gitaly-ssh: not found
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
September 10, 2018 08:35 -> INFO -> MergeRequests::RebaseService info (<redacted>): rebase started
September 10, 2018 08:35 -> ERROR -> MergeRequests::RebaseService error (<redacted>): Rebase failed. Please rebase locally
September 10, 2018 08:35 -> ERROR -> MergeRequests::RebaseService error (<redacted>): /gitaly-ssh upload-pack: 1: /gitaly-ssh upload-pack: /gitaly-ssh: not found
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by solidnerd** [comment]
Hey at all,

I think @xasx has found a temporary workaround for your problem https://github.com/sameersbn/docker-gitlab/issues/1721#issuecomment-419417829 . If this fix your problem let me know.

**Comment by tvtamas** [comment]
Hey @solidnerd,

Thanks for the tip, the workaround fixed the rebase issue for us.

**Comment by solidnerd** [comment]
Hey at all it should be fix with `11.3.0` try it out ;) otherwise reopen this again.
