### ISSUE TITLE
UNICORN_TIMEOUT not respected

### ISSUE THREAD

**Issue by fernandoneto** [sameersbn/docker-gitlab#539]
Im my logs `/var/logs/gitlab/gitlab/unicorn.stderr.log` im getting this outputs;

```bash
W, [2015-12-16T12:31:48.758414 #1286]  WARN -- : #<Unicorn::HttpServer:0x00000001d137c8>: worker (pid: 1286) exceeds memory limit (246697984.0 bytes > 246147601 bytes)
W, [2015-12-16T12:31:48.765012 #1286]  WARN -- : Unicorn::WorkerKiller send SIGQUIT (pid: 1286) alive: 43 sec (trial 1)
I, [2015-12-16T12:31:49.315748 #801]  INFO -- : reaped #<Process::Status: pid 1286 exit 0> worker=0
I, [2015-12-16T12:31:49.326623 #1290]  INFO -- : worker=0 ready
W, [2015-12-16T12:32:00.785894 #1290]  WARN -- : #<Unicorn::HttpServer:0x00000001d137c8>: worker (pid: 1290) exceeds memory limit (237690880.0 bytes > 209961167 bytes)
W, [2015-12-16T12:32:00.787873 #1290]  WARN -- : Unicorn::WorkerKiller send SIGQUIT (pid: 1290) alive: 9 sec (trial 1)
I, [2015-12-16T12:32:01.034564 #801]  INFO -- : reaped #<Process::Status: pid 1290 exit 0> worker=0
I, [2015-12-16T12:32:01.041455 #1294]  INFO -- : worker=0 ready
W, [2015-12-16T12:32:19.526660 #1258]  WARN -- : #<Unicorn::HttpServer:0x00000001d137c8>: worker (pid: 1258) exceeds memory limit (257744896.0 bytes > 257527500 bytes)
W, [2015-12-16T12:32:19.526880 #1258]  WARN -- : Unicorn::WorkerKiller send SIGQUIT (pid: 1258) alive: 375 sec (trial 1)
I, [2015-12-16T12:32:20.007997 #801]  INFO -- : reaped #<Process::Status: pid 1258 exit 0> worker=2
I, [2015-12-16T12:32:20.023054 #1302]  INFO -- : worker=2 ready
W, [2015-12-16T12:32:20.181617 #1294]  WARN -- : #<Unicorn::HttpServer:0x00000001d137c8>: worker (pid: 1294) exceeds memory limit (255053824.0 bytes > 241133847 bytes)
W, [2015-12-16T12:32:20.181826 #1294]  WARN -- : Unicorn::WorkerKiller send SIGQUIT (pid: 1294) alive: 17 sec (trial 1)
I, [2015-12-16T12:32:20.748064 #801]  INFO -- : reaped #<Process::Status: pid 1294 exit 0> worker=0
I, [2015-12-16T12:32:20.774018 #1306]  INFO -- : worker=0 ready
W, [2015-12-16T12:32:34.458791 #1302]  WARN -- : #<Unicorn::HttpServer:0x00000001d137c8>: worker (pid: 1302) exceeds memory limit (240132096.0 bytes > 235034191 bytes)
W, [2015-12-16T12:32:34.458959 #1302]  WARN -- : Unicorn::WorkerKiller send SIGQUIT (pid: 1302) alive: 12 sec (trial 1)
I, [2015-12-16T12:32:35.275958 #801]  INFO -- : reaped #<Process::Status: pid 1302 exit 0> worker=2
I, [2015-12-16T12:32:35.299143 #1314]  INFO -- : worker=2 ready
W, [2015-12-16T12:32:39.928360 #1254]  WARN -- : #<Unicorn::HttpServer:0x00000001d137c8>: worker (pid: 1254) exceeds memory limit (249618432.0 bytes > 249410537 bytes)
W, [2015-12-16T12:32:39.932039 #1254]  WARN -- : Unicorn::WorkerKiller send SIGQUIT (pid: 1254) alive: 407 sec (trial 1)
I, [2015-12-16T12:32:40.931075 #801]  INFO -- : reaped #<Process::Status: pid 1254 exit 0> worker=1
I, [2015-12-16T12:32:40.950301 #1318]  INFO -- : worker=1 ready

```

As you can see some of worker's stay up more than 60sec, but in gitlab unicorn [documentation](https://about.gitlab.com/2015/06/05/how-gitlab-uses-unicorn-and-unicorn-worker-killer/) they say if a worker stay up more than 60 sec the master worker must kill him.

**Comment by fernandoneto** [comment]
ping @sameersbn

**Comment by sameersbn** [comment]
@fernandoneto We are only setting `UNICORN_TIME` in `unicorn.rb`, from that point on unicorn should exhibit the expected behaviour. I will investigate it though.

**Comment by fernandoneto** [comment]
I will try to explain you what my issue.
Everytime one of the developers of our team makes a MR it takes a long time to appear ( 1h and sometimes more ). We are facing the same problem with build's triggered by tag's. 
I creat a repo to make some tests with  `README.md` only and when i try fork it to my user the process takes more than a hour. 
As you can see in `sidekiq.log`  the fork process start ate 16:29 and more than one hour it doesn't finish yet.

```bash
2015-12-22T16:29:54.120Z 801 TID-7mots RepositoryForkWorker JID-288a2dcddd90225c53b55f12 INFO: start
2015-12-22T16:32:35.745Z 801 TID-91wmg PostReceive JID- INFO: done: 10723.85 sec
2015-12-22T16:41:22.487Z 801 TID-91wmg PostReceive JID- INFO: start
2015-12-22T17:03:38.407Z 801 TID-9u8vc PostReceive JID- INFO: done: 12519.32 sec
2015-12-22T17:19:11.457Z 801 TID-9u8vc ProjectServiceWorker JID-f4fd4b2cda2b5f9d71f49051 INFO: start
2015-12-22T17:19:11.474Z 801 TID-7dmqc ProjectCacheWorker JID-22cfe6af5c16bb3804f4a25e INFO: start
2015-12-22T17:34:41.616Z 801 TID-9s6h0 PostReceive JID- INFO: done: 11147.723 sec
2015-12-22T17:34:41.617Z 801 TID-98fik ProjectServiceWorker JID-2957b38bcf56b73f15fc336a INFO: done: 10243.003 sec
2015-12-22T17:34:41.617Z 801 TID-9r36k ProjectCacheWorker JID-d2e97f845deff3db5257aeda INFO: done: 10242.986 sec
2015-12-22T17:34:41.617Z 801 TID-9sz6c ProjectServiceWorker JID-c5e717d14848ef0ca44049be INFO: done: 9313.251 sec
2015-12-22T17:34:41.617Z 801 TID-9qsuw ProjectCacheWorker JID-c5dde439fe2ff7f9a9c2f1a0 INFO: done: 9313.247 sec
2015-12-22T17:34:41.617Z 801 TID-808bs ProjectServiceWorker JID-41848f33bdf3694c946ff7b8 INFO: done: 8379.269 sec
2015-12-22T17:34:41.617Z 801 TID-973xs ProjectCacheWorker JID-433e94b20d2b840c18331485 INFO: done: 8379.255 sec
2015-12-22T17:34:41.624Z 801 TID-7n2gw PostReceive JID- INFO: done: 7746.919 sec
2015-12-22T17:35:51.943Z 801 TID-973xs PostReceive JID- INFO: start
```



Gitlab version:
![captura de ecra de 2015-12-22 17 42 58](https://cloud.githubusercontent.com/assets/6515784/11961872/8850f5e6-a8d3-11e5-9088-1d4e7592f199.png)

**Comment by sameersbn** [comment]
This is very odd behaviour. I checked the unicorn timeout option and setting it in unicorn.rb is all that is required. Can you check things like the available system resources, cpu load, etc. Could be possible that the CPU is under heavy load and/or RAM is being swapped out relatively frequently.

It may also be possible that the 60 sec timeout is too low.  Maybe the MR is large and GitLab requires more time to process it (again this could be because of CPU load issues). In which case if the worker is killed, it will start over and this will go over and over. You may want to try raising `UNICORN_TIMEOUT` parameter to a higher value to see if it resolves long time to create MR issue.

Lastly, try upgrading to newer releases, maybe it was a known issue that has been resolved.

If these recommendations do not resolve the issue, then you should consider this to be very severe and maybe the resolution would be to setup GitLab from scratch. There could be some database related issues that could be confusing gitlab. BTW, I hope that you are using PostgreSQL as the database backend. Possibly you could report the issue upstream as well.

Do let me know if any of these suggestions help.

**Comment by fernandoneto** [comment]
I did some more tests and discovered a possible problem in sidekiq porcess. For some reason the runners are getting jammed.

**Comment by sameersbn** [comment]
Any update on this?

**Comment by fernandoneto** [comment]
@sameersbn no the problem persist in the last version of gitlab. I think this issue is gitlab related because i found some other people with the same problem running out of docker container's.

**Comment by fernandoneto** [comment]
@sameersbn i think someone can found the root of the problem. 
take a look ate [this](https://gitlab.com/gitlab-org/gitlab-ce/issues/3661#note_3127905) issue in gitlab.
At the moment we are not using gitlab so i can give you any feedback.

**Comment by sameersbn** [comment]
Closing for now.
